github: handle error in commit message
Handles the error like below:
```
  Traceback (most recent call last):
     File "/opt/qa/github/handle_github.py", line 187, in <module>
       main(ARGS.repo, ARGS.dry_run, ARGS.comment_file)
     File "/opt/qa/github/handle_github.py", line 165, in main
       github.comment_on_issues(newissues, commit_msg)
     File "/opt/qa/github/handle_github.py", line 47, in comment_on_issues
       self._comment_on_issue(issue['id'], comment)
   TypeError: string indices must be integers
```

This was not noticed before because we returned 'issues' as is, when patchset is 1.

Signed-off-by: Amar Tumballi <amarts@redhat.com>